apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-cd
  template:
    metadata:
      labels:
        app: argo-cd
    spec:
      containers:
      - name: argo-cd
        image: argoproj/argocd:latest
        ports:
        - containerPort: 8080